//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SATEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class SATEditorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SATEditorSettings defaultInstance = ((SATEditorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SATEditorSettings())));
        
        public static SATEditorSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
